# Development environment with SQLite

services:
  kanban-board:
    container_name: kanban-board
    ports:
      - "3001:3001"
      - "5173:5173"  # Vite dev server port
    environment:
      - PORT=3001
      - HOST=0.0.0.0
    volumes:
      # Persistent database storage
      - kanban_data:/app/data
      # Development logs
      - kanban_logs:/app/logs
    networks:
      - kanban-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  kanban_data:
    driver: local
  kanban_logs:
    driver: local

networks:
  kanban-network:
    driver: bridge