# Development environment with SQLite

services:
  kanban-board:
    build:
      context: .
      target: development
    container_name: kanban-board-dev
    ports:
      - "3001:3001"
      - "5173:5173"  # Vite dev server port
    environment:
      - NODE_ENV=development
      - PORT=3001
      - HOST=0.0.0.0
      - DB_TYPE=sqlite
      - DB_FILE=/app/data/kanban-dev.db
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      - /app/frontend/node_modules
      # Persistent database storage
      - kanban_data:/app/data
      # Development logs
      - kanban_logs:/app/logs
    networks:
      - kanban-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  kanban_data:
    driver: local
  kanban_logs:
    driver: local

networks:
  kanban-network:
    driver: bridge