# Override file for local development
# This file is automatically used by docker-compose for development overrides

services:
  kanban-board:
    # Enable development mode with hot reload
    command: npm run dev:all
    environment:
      - NODE_ENV=development
      - DEBUG=kanban:*
    # Enable debugging
      - NODE_OPTIONS=--inspect=0.0.0.0:9229
    # Mount source code for live reload
    volumes:
      - .:/app
      - /app/node_modules
      - /app/frontend/node_modules
    # Expose additional ports for development
    ports:
      - "3001:3001"  # MCP server
      - "5173:5173"  # Vite dev server
      - "9229:9229"  # Node.js debugging port